ci/cd: Disable Fedora 30 due to missing ipython package
Error message:

$ dnf install gcc gcc-c++ python python-devel ccache gsl gsl-devel libgcrypt gtk3 gtk3-devel sqlite sqlite-devel libxml2 libxml2-devel openmpi openmpi-devel boost-devel pygobject3-devel python3-gobject gobject-introspection-devel goocanvas2-devel graphviz-devel graphviz ipython --assumeyes
Fedora Modular 30 - x86_64                      3.2 MB/s | 2.7 MB     00:00
Fedora Modular 30 - x86_64 - Updates            4.8 MB/s | 4.1 MB     00:00
Fedora 30 - x86_64 - Updates                    9.0 MB/s |  24 MB     00:02
Fedora 30 - x86_64                              9.9 MB/s |  70 MB     00:07
Package libgcrypt-1.8.5-1.fc30.x86_64 is already installed.
Package libxml2-2.9.9-2.fc30.x86_64 is already installed.
No match for argument: ipython
Error: Unable to find a match: ipython

From https://gitlab.com/nsnam/ns-3-dev/-/jobs/535839400

The funny thing is that the same line works for Fedora 29 and 31.